config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  resources :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/index.html.erb
<br />
<br />

<div class="jumbotron text-center">
  <h1>Welcome to #Products Homepage</h1>
  <p>Resize this responsive page to see the effect!</p>
</div>


<p>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Login
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
  <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PraticeBootstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>

  <body>
  <div class="main-navbar">
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <%= link_to "Homepage", root_path, class: 'navbar_link' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <%= link_to "Products", products_path, class: 'navbar_link' %>
      </li>
      <li class="nav-item">
      <%= link_to "Users", users_path, class: 'navbar_link' %>
      </li>
    </ul>
  </div>
</nav>
</div>

<div class="main-container">
    <%= yield %>

    </div>
  

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/index.html.erb
<%= new_rand = rand(1..100) %>


<div class="card-container">
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://picsum.photos/200/300?random=11" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Product#1</h5>
          <p class="card-text">Some quick example text to build on the Product#1 and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://picsum.photos/200/300?random=12" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Product#2</h5>
          <p class="card-text">Some quick example text to build on the Product#2 and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
    </div>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://picsum.photos/200/300?random=13" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Product#3</h5>
          <p class="card-text">Some quick example text to build on the Product#3 and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://picsum.photos/200/300?random=14" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Product#4</h5>
          <p class="card-text">Some quick example text to build on the Product#4 and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://picsum.photos/200/300?random=15" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Product#5</h5>
          <p class="card-text">Some quick example text to build on the Product#5 and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<br />
<br />
<br />
<br />
<br />
<br />

<div class="row">
  <div class="col-sm-2 sidebar">
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
    <li> #item </li>
  </div>

  <div class="col-sm-8">
  <div class="container">
<div class="col-md-offset-3">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Price</th>
      <th scope="col">Purchased the</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Product#1</td>
      <td>8.12€</td>
      <td>11/12/2030 : 11:30 pm</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Product#2</td>
      <td>6.02€</td>
      <td>11/12/2030 : 15:03 pm</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Product#3</td>
      <td>11/12/2030 : 10:50 pm</td>
    </tr>
  </tbody>
</table>
</div>
</div>
  </div>

  <div class="col-sm-2 sidebar">
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  <li> #item </li>
  </div>


</div>